version: '3.5'

services:
  # A local blockchain instance
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000 --gasLimit=8000000
    ports:
      - "8545:8545"
    networks:
      - merkle_tree_network

  # The main microservice for reconstructing a merkle tree
  merkle-tree:
    build:
      context: ./merkle-tree
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
      - mongo-merkle-tree
    volumes: # ensure relative paths are correct if embedding this microservice in another application:
      - ./merkle-tree/src:/app/src
      - ./merkle-tree/config:/app/config # mount point might be different if configuring from another application
      - ./merkle-tree/test:/app/test
      - ./merkle-tree/.babelrc:/app/.babelrc
      - ./merkle-tree/setup-mongo-acl-for-new-users.js:/app/setup-mongo-acl-for-new-users.js
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./merkle-tree/contracts/:/app/contracts:delegated # required if doing a 'local' deployment
      # - ./merkle-tree/build/:/app/build # required if doing a 'local' deployment
    ports:
      - "9000:80"
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      DEPLOYER_HOST: http://deployer # replace with external microservice's name
      DEPLOYER_PORT: 80
    networks:
      - merkle_tree_network

  # The database storing the merkle tree
  mongo-merkle-tree:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - ./merkle-tree/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo-merkle-tree-volume:/data/db
    networks:
      - merkle_tree_network

  # The deployer microservice is an example of a microservice which might deploy a merkle tree smart contract.
  deployer:
    build:
      context: ./deployer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
      - merkle-tree
    volumes:
      - ./deployer/src:/app/src
      - ./deployer/config:/app/config
      - ./deployer/test:/app/test
      - ./deployer/.babelrc:/app/.babelrc
      - ./deployer/contracts/:/app/contracts:delegated
      - ./deployer/build/:/app/build
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      MERKLE_TREE_HOST: http://merkle-tree
      MERKLE_TREE_PORT: 80
      DEPLOYER_HOST: http://deployer ## included so it can lazily find itself
      DEPLOYER_PORT: 80
    networks:
      - merkle_tree_network

volumes:
  mongo-merkle-tree-volume: {}

networks:
  merkle_tree_network:
    name: merkle_tree_network
